config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # called on an instance @person.full_name
  def full_name
    "#{self.first_name} #{self.last_name}"

 end
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all

  end

  def show
    @person = Person.find(params[:id])
  
  end

  def new
    @person = Person.new
  end


  def create
    @person = Person.new(people_params)
 
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
  
    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end
  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end
 
  private
 
    def people_params
      params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<h3><%= link_to 'Home', root_path %>

<%= link_to 'People', people_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailPeople</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<br><h1>Edit Person</h1><br>
<%= form_for @person do |f| %>
 <h2> <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br>
  <%= f.label :age %>
  <%= f.text_field :age %>
<br>
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
<br>
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
<br>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
<br>
  <%= f.label :alive %>
  <%= f.select :alive, options_for_select([['Yes', true], ['No', false]]) %>
<br>

  <%= f.submit %></h2>
<% end %>

app/views/people/index.html.erb
<h1> People </h1>
<p><%= link_to 'Create A Person', new_person_path %></p>
<% @people.each do |person| %>
  <h2><%= person.full_name  %></h2>
  <%= link_to 'Details', person_path(person) %>
  <%= link_to 'Edit Person', edit_person_path(person) %>
  ️<%= link_to 'Destroy Person', person, method: :delete %>🙅‍♂️
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  
  <%= f.label :alive %> 
  <%= f.select :alive, options_for_select([['Yes', true], ['No', false]]) %>
  
  <%= f.submit %>
  <% end %>
  
        

app/views/people/show.html.erb
<h1><%= @person.full_name %></h1>
<h3><%= "Age" %></h3>
<p><%= @person.age %></p><br>
<h3><%= "Hair Color" %></h3>
<p><%= @person.hair_color %></p><br>
<h3><%= "Eye Color" %></h3>
<p><%= @person.eye_color %></p><br>
<h3><%= "Gender" %></h3>
<p><%= @person.gender %></p><br>
<h3><%= "alive?" %></h3>
<p><%= @person.alive %></p><br>

<%= link_to 'Back', people_path %>

app/views/static_pages/home.html.erb
<h1>People Assignment</h1>
<p>Purple people eaters🍾🍾</p>